### ISSUE TITLE
Does this work with EE2?

### ISSUE THREAD

**Issue by trexchard** [EllisLab/Allow-Eecode#3]
I'm trying to install this on a site using Expression Engine 2. The ReadMe does not seems to match up with the file structure of EE2.

**Comment by kevincupp** [comment]
Yes, just download the code from the EE2 branch:

https://github.com/EllisLab/Allow-Eecode/tree/2.x

**Comment by trexchard** [comment]
And what about the install location? Third party, module, or plugin?

**Comment by kevincupp** [comment]
All add-ons you download go into the third_party directory regardless.

**Comment by trexchard** [comment]
Thanks @kevincupp!
